# Generated by Django 4.2.10 on 2024-06-04 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('nombre_titular', models.CharField(blank=True, max_length=50, null=True)),
                ('img_jpg', models.ImageField(upload_to='blog/', verbose_name='Imagen JPG')),
                ('img_webp', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen WEBP')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=260)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
