# Generated by Django 4.2.10 on 2024-06-04 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='images/')),
                ('descripcion', models.CharField(max_length=260)),
                ('contentido', models.TextField()),
                ('habitaciones', models.IntegerField()),
                ('wc', models.IntegerField()),
                ('garaje', models.IntegerField()),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('vendido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientes')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propiedades')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad_Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propiedades')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendedores')),
            ],
        ),
    ]
